// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package view

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Index() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<header><h1 class=\"text-center text-3xl font-bold\">Hello, World</h1></header><div class=\"flex justify-center mt-10\"><!-- HTMX here --><button hx-get=\"/foo\" class=\"btn bg-green-800 p-4 rounded-lg\">FOOaaaas</button></div><div class=\"container\"><h1>Image Processing</h1><p>Upload an image to process</p><div class=\"grid-view\"><div class=\"grid-item image-input-preview\"><h2>Image Preview</h2><img id=\"inputImage\"></div><div class=\"grid-item image-selector\"><input type=\"file\" accept=\"image/*\" id=\"imageInputForm\"> <button id=\"processBtn\">Process Image</button></div><div class=\"grid-item image-output-preview\"><h2>Image Output</h2><img id=\"outputImage\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
